update workflow

diff --git a/.github/workflows/manual.yml b/.github/workflows/manual.yml
--- a/.github/workflows/manual.yml
+++ b/.github/workflows/manual.yml
@@ -1,28 +1,18 @@
-# This is a basic workflow to help you get started with Actions
+name: Push To YC CR And Deploy to YC VM
 
-name: Push To Yandex Cloud CR
-
-# Controls when the action will run.
 on:
   release:
     types: [created]
 
-  # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
   build:
-    # The type of runner that the job will run on
     runs-on: ubuntu-latest
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v2
 
-      # Runs a single command using the runners shell
       - name: Yandex Cloud CR "Login" Action for GitHub Actions
         uses: yc-actions/yc-cr-login@v0.1-alpha
         with:
@@ -41,31 +31,32 @@ jobs:
             .
           docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG
 
-      - name: Deploy
-        run: |
-          mkdir -p ~/.ssh/
-          echo "${SSH_PRIVATE_KEY}" > ../private.key
-          sudo chmod 600 ../private.key
-          echo "${SSH_KNOWN_HOSTS}" > ~/.ssh/known_hosts
-          
-          ssh -i $SSH_KEY_PATH $VM_USER@$VM_HOST CR_REGISTRY=$CR_REGISTRY CR_REPOSITORY=$CR_REPOSITORY IMAGE_TAG=$IMAGE_TAG GITHUB_RUN_NUMBER=$GITHUB_RUN_NUMBER 'bash -s' < .github/workflows/scripts/deploy-ssh.sh
+  deploy:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+    - name: Deploy
+      run: |
+        mkdir -p ~/.ssh/
+        echo "${SSH_PRIVATE_KEY}" > ../private.key
+        sudo chmod 600 ../private.key
+        echo "${SSH_KNOWN_HOSTS}" > ~/.ssh/known_hosts
+        
+        ssh -i $SSH_KEY_PATH $VM_USER@$VM_HOST CR_REGISTRY=$CR_REGISTRY CR_REPOSITORY=$CR_REPOSITORY IMAGE_TAG=$IMAGE_TAG GITHUB_RUN_NUMBER=$GITHUB_RUN_NUMBER 'bash -s' < .github/workflows/scripts/deploy-ssh.sh
+        
+        exit_code=$?
+        echo exit code: $exit_code          
+        if [[ "$exit_code" = "1" ]]; then
+          echo "Deploy failed"
+          test $exit_code -ne 0 && exit $exit_code
+        fi
+      env:
+        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
+        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
+        SSH_KEY_PATH: ${{ github.workspace }}/../private.key
+        VM_USER: ${{ secrets.VM_USER }}
+        VM_HOST: ${{ secrets.VM_HOST }}
+        CR_REGISTRY: ${{ secrets.CR_REGISTRY }}
+        CR_REPOSITORY: yc-cr-creator-sticker-frontend
+        IMAGE_TAG: ${{ github.sha }}
 
-          exit_code=$?
-          echo exit code: $exit_code          
-          if [[ "$exit_code" = "1" ]]; then
-            echo "Deploy failed"
-            test $exit_code -ne 0 && exit $exit_code
-          fi
-
-#          exit_code=$?
-#          echo $msg
-#          test $exit_code -ne 0 && exit $exit_code
-        env:
-          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
-          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
-          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
-          VM_USER: ${{ secrets.VM_USER }}
-          VM_HOST: ${{ secrets.VM_HOST }}
-          CR_REGISTRY: ${{ secrets.CR_REGISTRY }}
-          CR_REPOSITORY: yc-cr-creator-sticker-frontend
-          IMAGE_TAG: ${{ github.sha }}
