update workflow

diff --git a/.github/workflows/manual.yml b/.github/workflows/manual.yml
--- a/.github/workflows/manual.yml
+++ b/.github/workflows/manual.yml
@@ -50,10 +50,11 @@ jobs:
           
           ssh -i $SSH_KEY_PATH $VM_USER@$VM_HOST CR_REGISTRY=$CR_REGISTRY CR_REPOSITORY=$CR_REPOSITORY IMAGE_TAG=$IMAGE_TAG GITHUB_RUN_NUMBER=$GITHUB_RUN_NUMBER 'bash -s' < .github/workflows/scripts/deploy-ssh.sh
 
-          echo $0
+          echo ?
+          echo $?
           
-          if [[ $? = 1 ]]; then \
-            echo "Deploy failed" \
+          if [[ $? = 1 ]]; then
+            echo "Deploy failed"
           fi
 
 #          exit_code=$?
